name: Yash Digital Assistance Service
on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome message
        run: echo "Welcome to Yash's Code Repository" > test123.txt
        
      - name: List All The Files
        run: ls
